### ISSUE TITLE
Standards für Wallbox-Einstellung

### ISSUE THREAD

**Issue by nischram** [nischram/E3dcGui#65]
Wegen der Größe meiner PV-Anlage benötige Standardeinstellungen für die Wallbox. Ich muss mit "Batterie zu Auto" immer spielen so halte ich es für Sinnvoll das man mit einem Schalter im Display 2-3 Standards aktivieren kann. Auch anderen im Haus können dann das Auto Laden ohne wieder unnötig aus dem Netz zu laden oder auch unnötig die Batterie leer zu ziehen.

Hier muss ich mal was für einbauen, damit es einfacher wird die Parameter die wichtig sind zu aktivieren.

**Comment by bs0001** [comment]
Hallo Nico,

noch habe ich kein e-Auto (wird sicherlich noch etwas dauern) aber die Wallbox ist zumindest schon mal vorhanden und betriebsbereit.
Was ich noch interessant finden würde wäre, dass man hinterlegen kann, welches Fahrzeug gerade geladen wird (falls man mehrere e-Autos hat, die an der Wallbox beladen werden).
Es besteht zwar die Möglichkeit per RFID-Erweiterung (gibts als Optionspaket) zu realisieren, doch lohnt sich m.E. sowas nur, wenn man einen Fuhrpark hat und eine Abrechnung benötigt.
Bei E3DC habe ich im Rahmen eines Tickets nachgefragt. Denen ist keine Möglichkeit bekannt, dass man ein Fahrzeug im System anlegen kann und die Ladevorgänge diesem zuordnet. Ich dachte nur, mit RFID müssen sie es ja auch einem Fahrzeug zuordnen können (oder Nummernschild oder sonst was, ist ja egal). Gefunden habe ich in den TAG nichts derzgleichen. Daher habe ich eine neue TAG-Liste angefordert (ob ich die bekomme, weiß ich nicht), da ja erst dieses Jahr die e-Mobility-Funktion implementiert wurde.
Ich fände es ziemlich gut, wenn es eine Möglichkeit gäbe (die vielleicht im E3DC-Portal auch nicht sichtbar ist), aber zumindest der Homematic bekannt sind und bspw. im CCU-Historian dann auch angezeigt werden kann, welches Fahrzeug sich wieviel Energie geschnappt hat.
Inwieweit sich beim Aktivieren der Wallbox eine ID ermitteln lässt, die dem Fahrzeug zuzuordnen ist, weiß ich nicht. Hab ja kein e-Auto.
Kannst ja auch mal überlegen, was Du von der Idee hältst. Für mich ist es aktuell von der Dringlichkeit niedrig für andere machts vielleicht schon eher Sinn. Dann kann es ja ggf. als zukünftige Entwicklung in den Backlog mit rein.

Lässt sich mittels Homematic dann auch sofern das Ladekabel am Auto steckt manuell eine Ladung starten, stoppen, wieder starten und stoppen oder ist das fahrzeugspezifisch, so dass man ggf. Ladekabel rausnehmen muss und wieder einstecken muss? Hab hier leider keine Erfahrungswerte.

Viele Grüße
Bernd

**Comment by nischram** [comment]
Hey, 
zum aktuellen Zeitpunkt ist für RFID im RSCP nichts möglich zumindest fehlen die TAGs in der Liste. wenn du was bekommst kann man ja mal schauen was möglich ist. ich kann es aber nicht testen denn ich habe die alte Wallbox ohne RFID Option.

Stoppen der Ladung ist möglich, aber bei meinem Fahrzeug muss ich dann immer erst das Kabel einmal abziehen bevor es wieder gestartet wird/werden kann.

Gruß Nico

**Comment by bs0001** [comment]
Hi Nico,

habe auch mal versucht im Portal zu debuggen. Bin hier allerdings auf keine TAGs gestoßen. Es könnte sein, dass die gesamte Abwicklung über das Rechenzentrum von E3DC läuft. Daher wahrscheinlich auch die Registrierung und Ausgabe von RFID-Karten nur über E3DC. Hab sowas wie Fahrzeuge anlegen, löschen etc. gefunden, allerdings wie gesagt alles ohne TAGs.
Muss ich mir bei Gelegenheit nochmal genauer ansehen. Aber erst mal die anderen Punkte noch erledigen, wenn Zeit ist.

Wo kann ich eigentlich sehen, ob bei einem eAuto eine Ladung gestoppt und später nochmal gestartet werden kann oder das Kabel abzuziehen?
Hab mal etwas rumgesucht, aber irgendwie nichts brauchbares gefunden. Wir liebäugeln mit einem Zoe derzeit.

Viele Grüße
Bernd

**Comment by bs0001** [comment]
Hallo Nico,

im E3DC-Portal gibt es unter "Smart-Funktionen" den Abschnitt "Ladepriorisierung".

Folgende Sachen lassen sich hier einstellen:
![image](https://user-images.githubusercontent.com/46260437/133961882-af76cc62-9be0-4bf7-971c-034e108a1d8c.png)

![image](https://user-images.githubusercontent.com/46260437/133961890-f30dc861-6ba0-401b-bd9b-32cbd745f0a1.png)

Habe im Browserdebugging folgendes dazu gefunden:
dataProxy.rscp.request(dataProxy.rscp.dataFactory("**EMS_REQ_BATTERY_TO_CAR_MODE**", "None",null)).then(
		function(data){
			if (data[0].value === 1) {
				controlvalues.cb_wallsave(true);				
			} else {
				controlvalues.cb_wallsave(false);
			}
		}
	).catch(
		function(err){
			console.error(err);
			if (err === -1){
				console.error("rscp error: "+err);								
			}
		}
	);
	dataProxy.rscp.request(dataProxy.rscp.dataFactory("**EMS_REQ_BATTERY_BEFORE_CAR_MODE**", "None",null)).then(
		function(data){
			if (data[0].value === 0 || data[0].value == "0") {
                $('#**batToCar**').fadeIn(500);
				controlvalues.cb_wallsaveSW(**true**);
			} else if (data[0].value === 1 || data[0].value == "1"){
                $('#**batToCar**').fadeOut(500);
				controlvalues.cb_wallsaveSW(**false**);
			}
		}
	).catch(
		function(err){
			console.error(err);
			if (err === -1){
				console.error("rscp error: "+err);								
			}
		}
);

Wäre cool, wenn Du diese Einstellung auch noch in die Wallbox-Steuerung bei Gelegenheit mit aufnehmen könntest.

Viele Grüße
Bernd

**Comment by nischram** [comment]
Hallo Bernd,

hier nochmal deine letzte Frage, da sie warum auch immer hier nicht zu sehen ist:
_

> Hallo Nico,
> 
> im E3DC-Portal gibt es unter "Smart-Funktionen" den Abschnitt "Ladepriorisierung".
> 
> Folgende Sachen lassen sich hier einstellen:
> image
> 
> image
> 
> Habe im Browserdebugging folgendes dazu gefunden:
> dataProxy.rscp.request(dataProxy.rscp.dataFactory("EMS_REQ_BATTERY_TO_CAR_MODE", "None",null)).then(
> function(data){
> if (data[0].value === 1) {
> controlvalues.cb_wallsave(true);
> } else {
> controlvalues.cb_wallsave(false);
> }
> }
> ).catch(
> function(err){
> console.error(err);
> if (err === -1){
> console.error("rscp error: "+err);
> }
> }
> );
> dataProxy.rscp.request(dataProxy.rscp.dataFactory("EMS_REQ_BATTERY_BEFORE_CAR_MODE", "None",null)).then(
> function(data){
> if (data[0].value === 0 || data[0].value == "0") {
> $('#batToCar').fadeIn(500);
> controlvalues.cb_wallsaveSW(true);
> } else if (data[0].value === 1 || data[0].value == "1"){
> $('#batToCar').fadeOut(500);
> controlvalues.cb_wallsaveSW(false);
> }
> }
> ).catch(
> function(err){
> console.error(err);
> if (err === -1){
> console.error("rscp error: "+err);
> }
> }
> );
> 
> Wäre cool, wenn Du diese Einstellung auch noch in die Wallbox-Steuerung bei Gelegenheit mit aufnehmen könntest.
> 
> Viele Grüße
> Bernd

_

Diese Einstellungen habe ich in der Wallboxsteuerung am Display drin, es ist auch schon per wbCheckHM möglich.

Viele Grüße Nico

**Comment by bs0001** [comment]
Hallo Nico,dieser Punkten hat sich erledigt. Hatte zu Beginn was nicht richtig verstanden. Funktioniert nun und ich konnte die Einstellungen nun über die Homematic vornehmen. Daher habe ich meinen Kommentar wieder gelöscht. Sorry für die Verwirrung. Viele Grüße Bernd 
-------- Ursprüngliche Nachricht --------Von: nischram ***@***.***> Datum: 20.09.21  18:22  (GMT+01:00) An: nischram/E3dcGui ***@***.***> Cc: bs0001 ***@***.***>, Comment ***@***.***> Betreff: Re: [nischram/E3dcGui] Standards für Wallbox-Einstellung (#65) 

Hallo Bernd,

hier nochmal deine letzte Frage, da sie warum auch immer hier nicht zu sehen ist:

_



Hallo Nico,

im E3DC-Portal gibt es unter "Smart-Funktionen" den Abschnitt "Ladepriorisierung".

Folgende Sachen lassen sich hier einstellen:

image

image

Habe im Browserdebugging folgendes dazu gefunden:

dataProxy.rscp.request(dataProxy.rscp.dataFactory("EMS_REQ_BATTERY_TO_CAR_MODE", "None",null)).then(

function(data){

if (data[0].value === 1) {

controlvalues.cb_wallsave(true);

} else {

controlvalues.cb_wallsave(false);

}

}

).catch(

function(err){

console.error(err);

if (err === -1){

console.error("rscp error: "+err);

}

}

);

dataProxy.rscp.request(dataProxy.rscp.dataFactory("EMS_REQ_BATTERY_BEFORE_CAR_MODE", "None",null)).then(

function(data){

if (data[0].value === 0 || data[0].value == "0") {

$('#batToCar').fadeIn(500);

controlvalues.cb_wallsaveSW(true);

} else if (data[0].value === 1 || data[0].value == "1"){

$('#batToCar').fadeOut(500);

controlvalues.cb_wallsaveSW(false);

}

}

).catch(

function(err){

console.error(err);

if (err === -1){

console.error("rscp error: "+err);

}

}

);

Wäre cool, wenn Du diese Einstellung auch noch in die Wallbox-Steuerung bei Gelegenheit mit aufnehmen könntest.

Viele Grüße

Bernd



_

Diese Einstellungen habe ich in der Wallboxsteuerung am Display drin, es ist auch schon per wbCheckHM möglich.

Viele Grüße Nico



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.



[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/nischram/E3dcGui/issues/65#issuecomment-923079426",

"url": "https://github.com/nischram/E3dcGui/issues/65#issuecomment-923079426",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by nischram** [comment]
Hey,
make für die Rückmeldung jetzt verstehe ich! Das du es gelöscht hast konnte ich nicht sehen. Aber alles Gut, es hätte ja auch einen Gute Idee sein können!

Genau bei der Menge der Einstellungen, liegt mein Problem für diesen Issue. Mit "Sonnenmodus", "Batterie vor Auto", "Batterie zu Auto" und dem "Max-Strom" kommt man doch schnell durcheinander und so habe ich doch mal die Batterie komplett ins Auto geschoben oder die Batterie geschont aber das Auto aus dem Netz geladen, obwohl ich eigentlich auf den nächsten Tag warten konnte. Dies will ich versuchen mit Standardeinstellungen zu umgehen. 

Ich habe noch deine Frage gefunden, ob man sehen kann das ein ein Auto getippt ist. Da ein Auto nicht direkt mit der Wallbox kommuniziert sieht man den Status vom Auto nicht, wenn also das Auto nicht mehr geladen werden möchten (Error) dann weiß die Walbox das oft nicht und man muss eher das Auto beobachten. Wenn mein Wagen im Error ist wird nur die Konnektivität nicht hergestellt aber einen Fehler sehe ich nicht in der WB oder am Speicher. 

Gruß Nico

**Comment by bs0001** [comment]
Hallo Nico,

ja ja, die Technik und dann macht sie manchmal doch was sie möchte. Akku leer ziehen. Ja, bestimmt, kann mir vorstellen, dass auch sowas mal vorkommt.

Ich habe vor das zukünftige e-Auto ebenfalls in die Homematic mit einzubinden. Nur wenn ich alle elementaren Gerätschaften im Haus in einem zentralen System habe, kann ich auch intelligent mit diesen kombiniert umgehen.
Derzeit steht der Renault Zoe recht hoch im Kurs. Schau mer mal.
Auf GitHub habe ich schon mal etwas rumgeschaut und 2 interessante Projekte gefunden. Muss mich natürlich dann genauer mit befassen, wenn das Thema e-Auto-Bestellung akut wird. Dann schau ich vorher schon mal, inwieweit ich es hinbekommen kann, die Autodaten in die Homematic zu bekommen als auch Schaltvorgänge vornehmen zu können.
Welches Fahrzeug hast Du denn?

Ich zeige Dir gerne mal meine Implementierung wenn Du Interesse daran hast. Ist realisiert mittels piVCCU3 auf einem Raspi, AIO Neo Creator für die App und CCU-Historian für die Auswertung (ebenfalls in die App integriert). Habe so ziemlich alles was wir im Hause haben integriert in die App. Schreib mich gerne direkt an.

Viele Grüße
Bernd

**Comment by bs0001** [comment]
Hallo Nico,
hier meine Kontaktadresse: bs0001@gmx.de
Schreib mich gerne direkt an per Mail.
Ich lösche diesen Kommentar wieder, damit es nicht öffentlich ist.
Viele Grüße
Bernd

**Comment by nischram** [comment]
Diese Idee verwerfe ich erstmal denn es gibt viel zu viele Optionen und so ein richtigen Standard habe ich nicht.
